# Copy to /etc/httpd/conf.d/DOMAIN.conf and replace placeholders.

<VirtualHost *:80>
    ServerName __DOMAIN__
    RewriteEngine On
    RewriteRule ^/(.*)$ https://__DOMAIN__/$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName __DOMAIN__

    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/__DOMAIN__/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/__DOMAIN__/privkey.pem

    ProxyRequests Off
    ProxyPreserveHost On
    SSLProxyEngine On

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader append X-Forwarded-For %{REMOTE_ADDR}s

    ProxyTimeout 60
    Timeout 60

    ProxyPass        /healthplix/fetch http://__VPN_HMS_IP__/healthplix/fetch
    ProxyPassReverse /healthplix/fetch http://__VPN_HMS_IP__/healthplix/fetch

    ErrorLog  /var/log/httpd/__DOMAIN__-healthplix-error.log
    CustomLog /var/log/httpd/__DOMAIN__-healthplix-access.log combined
</VirtualHost>
