<?php $rows = $rows ?? []; ?>
<section class="content">
    <div class="card"><div class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2"><div><h5 class="mb-0"><i class="bi bi-clipboard2-pulse me-2"></i>IPD Admission Examination Fields</h5><small class="text-muted">Enabled fields appear in Discharge Management → Examination on Admission. Existing saved values are retained.</small></div><button type="button" class="btn btn-sm btn-outline-secondary" onclick="load_form_div('<?= base_url('setting/admin') ?>','maindiv','Admin Panel')"><i class="bi bi-arrow-left me-1"></i>Admin Panel</button></div>
        <div class="card-body"><div id="exam_field_notice"></div><form id="exam_field_form" class="row g-3 align-items-end"><input type="hidden" name="id" id="exam_field_id" value="0"><?= csrf_field() ?>
            <div class="col-md-2"><label class="form-label">Field Code</label><input class="form-control" name="col_code" id="exam_field_code" maxlength="50" placeholder="LEFT_DIAGNOSIS" required></div>
            <div class="col-md-2"><label class="form-label">Field Name</label><input class="form-control" name="col_name" id="exam_field_name" maxlength="50" placeholder="left_diagnosis" required></div>
            <div class="col-md-3"><label class="form-label">Display Label</label><input class="form-control" name="col_description" id="exam_field_label" maxlength="50" placeholder="Left Diagnosis" required></div>
            <div class="col-md-2"><label class="form-label">Input Type</label><select class="form-select" name="col_type" id="exam_field_type"><option value="0">Single-line text</option><option value="1">Long text</option><option value="2">Number</option><option value="4">Select list</option></select></div>
            <div class="col-md-1"><label class="form-label">Group</label><select class="form-select" name="cat_group" id="exam_field_group"><option value="1">General</option><option value="2">Other</option></select></div>
            <div class="col-md-1"><label class="form-label">Order</label><input class="form-control" name="display_order" id="exam_field_order" type="number" min="0" step="1" value="0"></div>
            <div class="col-md-1"><label class="form-label">Enabled</label><select class="form-select" name="is_active" id="exam_field_active"><option value="1">Yes</option><option value="0">No</option></select></div>
            <div class="col-md-3"><label class="form-label">Unit</label><input class="form-control" name="col_unit" id="exam_field_unit" maxlength="50" placeholder="mmHg"></div>
            <div class="col-md-6"><label class="form-label">Default / Select Options</label><input class="form-control" name="col_pre_value" id="exam_field_values" placeholder="For select: Normal|Abnormal|Not recorded"></div>
            <div class="col-md-3 d-flex gap-2"><button type="submit" class="btn btn-primary flex-grow-1"><i class="bi bi-save me-1"></i>Save Field</button><button type="button" class="btn btn-outline-secondary" id="exam_field_clear">Clear</button></div>
        </form></div></div>
    <div class="card mt-3"><div class="card-body table-responsive"><table class="table table-sm table-striped align-middle mb-0"><thead class="table-light"><tr><th>Order</th><th>Code</th><th>Label</th><th>Type</th><th>Group</th><th>Unit</th><th>Status</th><th></th></tr></thead><tbody><?php foreach ($rows as $row) : ?><tr data-row='<?= esc(json_encode($row), 'attr') ?>'><td><?= (int) ($row['display_order'] ?? 0) ?></td><td><code><?= esc($row['col_code'] ?? '') ?></code></td><td><?= esc($row['col_description'] ?? '') ?></td><td><?= ['Text', 'Long text', 'Number', 'Auto', 'Select'][(int) ($row['col_type'] ?? 0)] ?? 'Text' ?></td><td><?= (int) ($row['cat_group'] ?? 1) === 2 ? 'Other' : 'General' ?></td><td><?= esc($row['col_unit'] ?? '') ?></td><td><span class="badge text-bg-<?= (int) ($row['is_active'] ?? 1) === 1 ? 'success' : 'secondary' ?>"><?= (int) ($row['is_active'] ?? 1) === 1 ? 'Enabled' : 'Disabled' ?></span></td><td class="text-end"><button type="button" class="btn btn-sm btn-outline-primary exam-field-edit">Edit</button> <button type="button" class="btn btn-sm btn-outline-<?= (int) ($row['is_active'] ?? 1) === 1 ? 'warning' : 'success' ?> exam-field-toggle" data-id="<?= (int) $row['id'] ?>"><?= (int) ($row['is_active'] ?? 1) === 1 ? 'Disable' : 'Enable' ?></button></td></tr><?php endforeach; ?></tbody></table></div></div>
</section>
<script>
(function () {
    var form = document.getElementById('exam_field_form');
    var notice = document.getElementById('exam_field_notice');
    function message(text, kind) { notice.innerHTML = '<div class="alert alert-' + kind + ' py-2">' + $('<div>').text(text).html() + '</div>'; }
    function reset() { form.reset(); $('#exam_field_id').val('0'); $('#exam_field_active').val('1'); $('#exam_field_order').val('0'); }
    $('#exam_field_clear').off('click.examFields').on('click.examFields', reset);
    $(document).off('click.examFields', '.exam-field-edit').on('click.examFields', '.exam-field-edit', function () { var row = $(this).closest('tr').data('row'); if (!row) return; $('#exam_field_id').val(row.id || 0); $('#exam_field_code').val(row.col_code || ''); $('#exam_field_name').val(row.col_name || ''); $('#exam_field_label').val(row.col_description || ''); $('#exam_field_type').val(String(row.col_type || 0)); $('#exam_field_group').val(String(row.cat_group || 1)); $('#exam_field_order').val(row.display_order || 0); $('#exam_field_active').val(String(typeof row.is_active === 'undefined' ? 1 : row.is_active)); $('#exam_field_unit').val(row.col_unit || ''); $('#exam_field_values').val(row.col_pre_value || ''); window.scrollTo({top: 0, behavior: 'smooth'}); });
    $(document).off('click.examFields', '.exam-field-toggle').on('click.examFields', '.exam-field-toggle', function () { var button = this; var payload = {}; payload['<?= csrf_token() ?>'] = $(form).find('input[name="<?= csrf_token() ?>"]').val(); $.post('<?= base_url('setting/admin/ipd-examination-fields/toggle') ?>/' + $(button).data('id'), payload, function (data) { if (!data || !data.ok) { message((data && data.message) || 'Unable to change field status.', 'danger'); return; } load_form_div('<?= base_url('setting/admin/ipd-examination-fields') ?>', 'maindiv', 'IPD Examination Fields'); }, 'json'); });
    $(form).off('submit.examFields').on('submit.examFields', function (event) { event.preventDefault(); $.post('<?= base_url('setting/admin/ipd-examination-fields/save') ?>', $(form).serialize(), function (data) { if (!data || !data.ok) { message((data && data.message) || 'Unable to save field.', 'danger'); return; } load_form_div('<?= base_url('setting/admin/ipd-examination-fields') ?>', 'maindiv', 'IPD Examination Fields'); }, 'json').fail(function () { message('Unable to save field.', 'danger'); }); });
})();
</script>