<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ComplaintsMasterSeeder extends Seeder
{
    public function run()
    {
        if (! $this->db->tableExists('complaints_master')) {
            return;
        }

        $json = <<<'JSON'
{
    "table": "complaints_master",
    "rows": [
        {"Code":1,"Name":"FEVER","show_in_short":1},
        {"Code":2,"Name":"PAIN JOINTS","show_in_short":1},
        {"Code":3,"Name":"PAIN EXTREMITIES","show_in_short":0},
        {"Code":4,"Name":"PAIN BACK","show_in_short":1},
        {"Code":5,"Name":"PAIN CHEST","show_in_short":1},
        {"Code":6,"Name":"PAIN","show_in_short":1},
        {"Code":7,"Name":"BREATHING DIFFICULTY","show_in_short":1},
        {"Code":8,"Name":"BREATHLESSNESS","show_in_short":0},
        {"Code":9,"Name":"PALPITATION","show_in_short":0},
        {"Code":10,"Name":"GHABRAHAT","show_in_short":0},
        {"Code":11,"Name":"EDEMA FEET","show_in_short":0},
        {"Code":12,"Name":"EDEMA GENERALISED","show_in_short":0},
        {"Code":13,"Name":"COUGH DRY","show_in_short":1},
        {"Code":14,"Name":"COUGH WITH EXPECTORATION","show_in_short":1},
        {"Code":15,"Name":"HAEMATEMESIS","show_in_short":0},
        {"Code":16,"Name":"HAEMOPTYSIS","show_in_short":0},
        {"Code":17,"Name":"APPETITE","show_in_short":0},
        {"Code":18,"Name":"VOMITING","show_in_short":1},
        {"Code":19,"Name":"ABDOMINAL DISTENSION","show_in_short":0},
        {"Code":20,"Name":"DIARRHOEA","show_in_short":0},
        {"Code":21,"Name":"CONSTIPATION","show_in_short":0},
        {"Code":22,"Name":"BLEEDING P\/V","show_in_short":1},
        {"Code":23,"Name":"BLEEDING P\/R, PAINLESS & IN DROPS OR STREAM","show_in_short":0},
        {"Code":24,"Name":"BLEEDING GUMS","show_in_short":0},
        {"Code":25,"Name":"BLEEDING","show_in_short":0},
        {"Code":26,"Name":"WATER BRASH","show_in_short":0},
        {"Code":27,"Name":"REGURGITATION","show_in_short":0},
        {"Code":28,"Name":"JAUNDICE","show_in_short":0},
        {"Code":29,"Name":"URINE WITH PASSAGE OF CLOTS","show_in_short":0},
        {"Code":30,"Name":"URINE","show_in_short":0},
        {"Code":31,"Name":"STOOL","show_in_short":0},
        {"Code":32,"Name":"STOOL BLACK","show_in_short":0},
        {"Code":33,"Name":"MELENA","show_in_short":0},
        {"Code":34,"Name":"BURNING EPIGASTRIUM","show_in_short":0},
        {"Code":35,"Name":"MICTURETION WITH BURNING","show_in_short":0},
        {"Code":36,"Name":"URINARY HASITANCY","show_in_short":0},
        {"Code":37,"Name":"URINARY PRECIPITANCY","show_in_short":0},
        {"Code":38,"Name":"MICTURETION WITH INCREASED FREQUENCY","show_in_short":0},
        {"Code":39,"Name":"RETENSION URINE","show_in_short":0},
        {"Code":40,"Name":"HAEMATURIA","show_in_short":0},
        {"Code":41,"Name":"L.M.P.","show_in_short":0},
        {"Code":42,"Name":"DYSMENORRHEA","show_in_short":0},
        {"Code":43,"Name":"AMENORRHEA","show_in_short":0},
        {"Code":44,"Name":"DISCHARGE P\/V","show_in_short":0},
        {"Code":45,"Name":"HEADACHE","show_in_short":1},
        {"Code":46,"Name":"EPILEPTIC FITS","show_in_short":0},
        {"Code":47,"Name":"GIDDINESS","show_in_short":0},
        {"Code":48,"Name":"VERTIGO","show_in_short":1},
        {"Code":49,"Name":"CONCIOUSNESS","show_in_short":0},
        {"Code":50,"Name":"ORIENTATION","show_in_short":0},
        {"Code":51,"Name":"VISION","show_in_short":0},
        {"Code":52,"Name":"BEHAVIOUR","show_in_short":0},
        {"Code":53,"Name":"SLEEP","show_in_short":0},
        {"Code":54,"Name":"HEARING","show_in_short":0},
        {"Code":55,"Name":"DYSPHAGIA","show_in_short":0},
        {"Code":56,"Name":"WEAKNESS","show_in_short":1},
        {"Code":57,"Name":"LETHARGINESS","show_in_short":0},
        {"Code":58,"Name":"PAIN IN ABDOMEN","show_in_short":1},
        {"Code":59,"Name":"NAUSEA","show_in_short":1},
        {"Code":60,"Name":"GENERAL WEAKNESS","show_in_short":0},
        {"Code":61,"Name":"PAIN IN KNEE JOINTS","show_in_short":0},
        {"Code":62,"Name":"NASAL DISCHARGE","show_in_short":0},
        {"Code":63,"Name":"URINE YELLOW COLORED","show_in_short":0},
        {"Code":64,"Name":"PAIN IN SINUS AREA","show_in_short":0},
        {"Code":65,"Name":"PAIN IN BOTH THUMBS","show_in_short":0},
        {"Code":66,"Name":"DRIPPING NOSE","show_in_short":0},
        {"Code":67,"Name":"SEMISOLID, BULKY MOTIONS","show_in_short":0},
        {"Code":68,"Name":"TINNITUS","show_in_short":0},
        {"Code":69,"Name":"PAPULAR ERRUPTION","show_in_short":0},
        {"Code":70,"Name":"MOTIONS","show_in_short":0},
        {"Code":71,"Name":"FAMILY H\/O","show_in_short":0},
        {"Code":72,"Name":"FAMILY H\/O PREMATURE CORONARY ARTRY DISEASE","show_in_short":0},
        {"Code":73,"Name":"FAMILY H\/O DYSLIPIDEMIA","show_in_short":0},
        {"Code":74,"Name":"XANTHOMAS","show_in_short":0},
        {"Code":75,"Name":"H\/O DIABETES","show_in_short":0},
        {"Code":76,"Name":"H\/O HYPOTHYROIDISM","show_in_short":0},
        {"Code":77,"Name":"WEIGHT LOSS","show_in_short":0},
        {"Code":78,"Name":"H\/O THROMBOEMBOLIC PHENOMENON","show_in_short":0},
        {"Code":79,"Name":"STOMATITIS","show_in_short":0},
        {"Code":80,"Name":"NECROLYTIC MIGRATING ERYTHEMA","show_in_short":0},
        {"Code":81,"Name":"H\/O FEVER SINCE OR FEW WEEKS BEFORE CONCEPTION","show_in_short":0},
        {"Code":82,"Name":"FEELING OF EXCESSIVE COLD","show_in_short":0},
        {"Code":83,"Name":"MENSTRUAL CYCLE","show_in_short":0},
        {"Code":84,"Name":"SWEATING","show_in_short":0},
        {"Code":85,"Name":"RETROSTERNAL PAIN OR HEAVINESS","show_in_short":0},
        {"Code":86,"Name":"H\/O SUCH PAIN ANY TIME PREVIOUSLY","show_in_short":0},
        {"Code":87,"Name":"PAIN INCREASES ON EXHERTION","show_in_short":0},
        {"Code":88,"Name":"PAIN CHEST INCREASES ON EXHERTION & RELEIVED BY REST","show_in_short":0},
        {"Code":89,"Name":"BREATHLESSNESS ON EXHERTION","show_in_short":0},
        {"Code":90,"Name":"NOCTURNAL ATTACK OF DYSPNEA","show_in_short":0},
        {"Code":91,"Name":"HEARTBURN","show_in_short":0},
        {"Code":92,"Name":"PAIN IN ABDOMEN ASSOCIATED WITH FREQUENT BOWEL MOVEMENTS","show_in_short":0},
        {"Code":93,"Name":"PAIN IN ABDOMEN ASSOCIATED WITH LOOSE STOOLS","show_in_short":0},
        {"Code":94,"Name":"PAIN IN ABDOMEN RELIEVED BY DEFECATION","show_in_short":0},
        {"Code":95,"Name":"SENSATION OF INCOMPLETE EVACUATION","show_in_short":0},
        {"Code":96,"Name":"MUCUS IN STOOLS","show_in_short":0},
        {"Code":97,"Name":"POSTPRANDIAL URGENCY FOR PASSING STOOL","show_in_short":0},
        {"Code":98,"Name":"ALTERED BOWEL HABITS","show_in_short":0},
        {"Code":99,"Name":"PAIN IN ABDOMEN, RADIATING TO BACK","show_in_short":0},
        {"Code":100,"Name":"PAIN IN ABDOMEN IMPROVES IN SUPINE POSITION","show_in_short":0},
        {"Code":101,"Name":"TACHYCARDIA","show_in_short":0},
        {"Code":102,"Name":"H\/O INFECTION LIKE PHARYNGITIS, TONSILITIS OR PYODERMA","show_in_short":0},
        {"Code":103,"Name":"URINE DARK","show_in_short":0},
        {"Code":104,"Name":"EDEMA PERIORBITAL","show_in_short":0},
        {"Code":105,"Name":"MALAISE","show_in_short":0},
        {"Code":106,"Name":"ANOREXIA","show_in_short":0},
        {"Code":107,"Name":"WHEEZING","show_in_short":0},
        {"Code":108,"Name":"FATIGUE","show_in_short":0},
        {"Code":109,"Name":"MYALGIA","show_in_short":0},
        {"Code":110,"Name":"SKIN RASH","show_in_short":0},
        {"Code":111,"Name":"CHANGE OF HAND COLOR ON EXPOSURE TO COLD","show_in_short":0},
        {"Code":112,"Name":"MOOD DISORDERS","show_in_short":0},
        {"Code":113,"Name":"CONFUSION","show_in_short":0},
        {"Code":114,"Name":"DELIRIUM","show_in_short":0},
        {"Code":115,"Name":"DISORIENTATION","show_in_short":0},
        {"Code":116,"Name":"PERIPHERAL NEUROPATHY SYMPTOMS","show_in_short":0},
        {"Code":117,"Name":"ABDOMINAL PAIN","show_in_short":0},
        {"Code":118,"Name":"PALLOR","show_in_short":0},
        {"Code":119,"Name":"ANEMIA","show_in_short":0},
        {"Code":121,"Name":"ACCIDENTAL INJURY","show_in_short":0},
        {"Code":122,"Name":"DEHYDRATION","show_in_short":0},
        {"Code":123,"Name":"BODYACHE","show_in_short":0},
        {"Code":124,"Name":"POLYURIA","show_in_short":0},
        {"Code":125,"Name":"POLYDIPSIA","show_in_short":0},
        {"Code":126,"Name":"H\/O OVER WEIGHT","show_in_short":0},
        {"Code":127,"Name":"TIREDNESS","show_in_short":0},
        {"Code":128,"Name":"SWELLING","show_in_short":0},
        {"Code":129,"Name":"BACK PAIN","show_in_short":0},
        {"Code":131,"Name":"COUGH WITH YELLOW EXPECTORATION","show_in_short":1},
        {"Code":132,"Name":"COUGH WITH WHITE EXPECTORATION","show_in_short":1},
        {"Code":133,"Name":"FEVER, CONTINUOUS","show_in_short":1},
        {"Code":134,"Name":"FEVER, INTERMITTENT","show_in_short":1},
        {"Code":135,"Name":"FEVER, REMITTANT","show_in_short":1},
        {"Code":136,"Name":"MICTURETION, PAINFUL","show_in_short":0},
        {"Code":137,"Name":"WEIGHT GAIN","show_in_short":0},
        {"Code":138,"Name":"MUSCLE WEAKNESS","show_in_short":0},
        {"Code":139,"Name":"COLD INTOLERANCE","show_in_short":0},
        {"Code":140,"Name":"HEAT INTOLERANCE","show_in_short":0},
        {"Code":141,"Name":"SWEATING INCREASED","show_in_short":0},
        {"Code":142,"Name":"FLUSHING","show_in_short":0},
        {"Code":143,"Name":"TREMORS","show_in_short":0},
        {"Code":144,"Name":"DIZZINESS","show_in_short":1},
        {"Code":145,"Name":"POSTURAL UNSTEADINESS","show_in_short":0},
        {"Code":146,"Name":"VISUAL DISTURBANCES","show_in_short":0},
        {"Code":147,"Name":"CRAMPS","show_in_short":0},
        {"Code":148,"Name":"IMPOTENCE","show_in_short":0},
        {"Code":149,"Name":"GYNAECOMASTIA","show_in_short":0},
        {"Code":150,"Name":"AMENORRHOEA","show_in_short":0},
        {"Code":151,"Name":"GALACTORRHOEA","show_in_short":0},
        {"Code":152,"Name":"EXCESS HAIR GROWTH","show_in_short":0},
        {"Code":153,"Name":"IRREGULAR BOWEL HABITS","show_in_short":0},
        {"Code":154,"Name":"BREATHING PAINFUL","show_in_short":0},
        {"Code":155,"Name":"COUGH SPASMODIC","show_in_short":0},
        {"Code":156,"Name":"DIARRHOEA, JUST INCREASED FREQUENCY","show_in_short":0},
        {"Code":157,"Name":"DIARRHOEA, WATERY LOOSE MOTIONS","show_in_short":0},
        {"Code":158,"Name":"DIARRHOEA, WATERY, RICE WATER","show_in_short":0},
        {"Code":159,"Name":"DIARRHOEA, WITH BLOOD & MUCUS","show_in_short":0},
        {"Code":160,"Name":"DYSPEPSIA","show_in_short":0},
        {"Code":161,"Name":"HICUPS","show_in_short":0},
        {"Code":162,"Name":"URINE, INCREASED FREQUENCY","show_in_short":0},
        {"Code":163,"Name":"LOSS OF LIBIDO","show_in_short":0},
        {"Code":164,"Name":"BURNING MICTURETION","show_in_short":0},
        {"Code":165,"Name":"DROWSINESS","show_in_short":0},
        {"Code":166,"Name":"JERKY MOVEMENTS OF LIMBS","show_in_short":0},
        {"Code":167,"Name":"H\/O FITS","show_in_short":0},
        {"Code":168,"Name":"FORGETFULLNESS","show_in_short":0},
        {"Code":169,"Name":"MEMORY","show_in_short":0},
        {"Code":170,"Name":"INCOMPREHENSION","show_in_short":0},
        {"Code":171,"Name":"DOUBLE VISION","show_in_short":0},
        {"Code":172,"Name":"DROOPING OF EYE LIDS","show_in_short":0},
        {"Code":173,"Name":"GAIT","show_in_short":0},
        {"Code":174,"Name":"BODY MOVEMENTS","show_in_short":0},
        {"Code":175,"Name":"FACIAL EXPRESSION","show_in_short":0},
        {"Code":176,"Name":"DROOLING OF SALIVA","show_in_short":0},
        {"Code":177,"Name":"BREATHELESSNESS","show_in_short":0},
        {"Code":178,"Name":"H\/O FEVER","show_in_short":0},
        {"Code":179,"Name":"TENESMUS","show_in_short":0},
        {"Code":180,"Name":"G.I. BLEEDING","show_in_short":0},
        {"Code":181,"Name":"ORAL ULCERS","show_in_short":0},
        {"Code":182,"Name":"GAIT UNSTEADY","show_in_short":0},
        {"Code":183,"Name":"RASHES","show_in_short":0},
        {"Code":184,"Name":"PLAQUE, RAISED ERYTHEMATOUS","show_in_short":0},
        {"Code":185,"Name":"ITCHING","show_in_short":0},
        {"Code":186,"Name":"RED, ERYTHEMATOUS LESIONS","show_in_short":0},
        {"Code":187,"Name":"HOARSENESS OF VOICE","show_in_short":0},
        {"Code":188,"Name":"DRIBBLING OF URINE","show_in_short":0},
        {"Code":189,"Name":"PAIN IN LEGS","show_in_short":0},
        {"Code":190,"Name":"THROAT PAIN","show_in_short":0},
        {"Code":191,"Name":"SNEEZING","show_in_short":0},
        {"Code":192,"Name":"THROAT IRRITATION","show_in_short":0},
        {"Code":193,"Name":"BLUISHNESS OF SKIN","show_in_short":0},
        {"Code":194,"Name":"LOW BLOOD PRESSURE","show_in_short":0},
        {"Code":195,"Name":"BURPING","show_in_short":0},
        {"Code":196,"Name":"INABILITY TO READ PROPERLY","show_in_short":0},
        {"Code":197,"Name":"INABILITY TO RECOGNISE","show_in_short":0},
        {"Code":199,"Name":"BALDNESS","show_in_short":0},
        {"Code":200,"Name":"EXCESSIVE FALLING OF HAIR","show_in_short":0},
        {"Code":201,"Name":"FAINTING FEELING","show_in_short":0},
        {"Code":202,"Name":"ABSENCE OF BLEEDING P\/V","show_in_short":0},
        {"Code":203,"Name":"LOSS OF MEMORY","show_in_short":0},
        {"Code":204,"Name":"PAIN DURING DAEFECATION","show_in_short":0},
        {"Code":205,"Name":"BLOOD IN STOOL","show_in_short":1},
        {"Code":206,"Name":"STIFFNESS","show_in_short":0},
        {"Code":208,"Name":"CYANOSIS","show_in_short":0},
        {"Code":209,"Name":"PIGMENTATION","show_in_short":0},
        {"Code":211,"Name":"BULLOUS ERRUPTION","show_in_short":0},
        {"Code":212,"Name":"RESTLESSNESS","show_in_short":0},
        {"Code":213,"Name":"LACK OF ATTENTION","show_in_short":0},
        {"Code":214,"Name":"POOR CONCENTRATION","show_in_short":0},
        {"Code":215,"Name":"POOR PERFORMANCE AT SCHOOL","show_in_short":0},
        {"Code":216,"Name":"LOW GRADES AT SCHOOL","show_in_short":0},
        {"Code":217,"Name":"EXCORIATIONS","show_in_short":0},
        {"Code":218,"Name":"GROWTH","show_in_short":0},
        {"Code":219,"Name":"ULCERS","show_in_short":0},
        {"Code":220,"Name":"INABILITY TO CLOSE EYES FULLY","show_in_short":0},
        {"Code":223,"Name":"HEADACHE FROM LAQST","show_in_short":0},
        {"Code":224,"Name":"HEADACHE FROM LAST 12 DAY","show_in_short":0},
        {"Code":226,"Name":"FEELING OF GRANDIOSE","show_in_short":0},
        {"Code":227,"Name":"IRRITABILITY","show_in_short":0},
        {"Code":228,"Name":"DEPRESSION","show_in_short":0},
        {"Code":229,"Name":"PSYCHOMOTOR ACTIVITY","show_in_short":0},
        {"Code":230,"Name":"IMPULSIVE","show_in_short":0},
        {"Code":232,"Name":"IRRITATION","show_in_short":1},
        {"Code":233,"Name":"PARESTHESIAS","show_in_short":0},
        {"Code":234,"Name":"BURNING","show_in_short":0},
        {"Code":235,"Name":"TENDERNESS","show_in_short":0},
        {"Code":236,"Name":"LUMP IN RT BREAST","show_in_short":0},
        {"Code":237,"Name":"PAIN ABDOMEN","show_in_short":0},
        {"Code":238,"Name":"WEAKNESS IN RT HALF OF BODY","show_in_short":0},
        {"Code":239,"Name":"PERIPHERAL CIRCULATORY FAILURE","show_in_short":0},
        {"Code":240,"Name":"PAIN IN EPIGASTRIUM","show_in_short":0},
        {"Code":241,"Name":"LACRIMATION","show_in_short":0},
        {"Code":242,"Name":"RHINORRHOEA","show_in_short":0},
        {"Code":243,"Name":"CONVULSIONS","show_in_short":0},
        {"Code":244,"Name":"RINGING IN EARS","show_in_short":0},
        {"Code":245,"Name":"TACHYPNEA","show_in_short":0},
        {"Code":246,"Name":"FAILS TO GROW","show_in_short":0},
        {"Code":247,"Name":"HEHRHR","show_in_short":0},
        {"Code":248,"Name":"HISTORY OF HAIE FAL","show_in_short":0},
        {"Code":249,"Name":"HISTORY OF HAIE FALL","show_in_short":0}
    ]
}
JSON;

        $decoded = json_decode($json, true);
        $rows = is_array($decoded['rows'] ?? null) ? $decoded['rows'] : [];
        if (empty($rows)) {
            return;
        }

        $table = $this->db->table('complaints_master');
        $now = date('Y-m-d H:i:s');

        foreach ($rows as $row) {
            $code = (int) ($row['Code'] ?? 0);
            $name = trim((string) ($row['Name'] ?? ''));
            if ($code <= 0 || $name === '') {
                continue;
            }

            $payload = [
                'Code' => $code,
                'Name' => $name,
                'show_in_short' => (int) ($row['show_in_short'] ?? 0),
                'is_active' => 1,
                'keywords' => strtolower($name),
                'updated_at' => $now,
            ];

            $exists = $this->db->table('complaints_master')->select('Code')->where('Code', $code)->get(1)->getRowArray();
            if ($exists) {
                $table->where('Code', $code)->update($payload);
                continue;
            }

            $payload['created_at'] = $now;
            $table->insert($payload);
        }
    }
}
