<?php
/** @var array<string, mixed> $case */
/** @var array<int, object> $doctors */
/** @var bool $can_schedule */
/** @var bool $can_status */
/** @var bool $can_postop */
$caseId = (int) ($case['id'] ?? 0);
$status = (string) ($case['status'] ?? 'requested');
?>
<h5><?= esc((string) ($case['request_no'] ?? 'OT Case')) ?> - <?= esc((string) ($case['procedure_name'] ?? '')) ?></h5>
<p class="small text-muted mb-3"><?= esc((string) ($case['department_name_snapshot'] ?? '')) ?> | Status: <?= esc(ucwords(str_replace('_', ' ', $status))) ?> | Call: <?= esc(ucwords(str_replace('_', ' ', (string) ($case['call_status'] ?? '')))) ?></p>
<?php if ($can_schedule) : ?>
<form class="ipd-ot-ajax-form border rounded p-3 mb-3" action="<?= site_url('ot/cases/' . $caseId) ?>" method="post" data-refresh="queue"><h6>Schedule / Reschedule</h6><?= csrf_field() ?><input type="hidden" name="action" value="<?= empty($case['scheduled_start_at']) ? 'schedule' : 'reschedule' ?>"><div class="row g-2">
<div class="col-md-4"><label class="form-label">Date &amp; Time</label><input type="datetime-local" name="scheduled_start_at" class="form-control" value="<?= esc(str_replace(' ', 'T', substr((string) ($case['scheduled_start_at'] ?? ''), 0, 16)), 'attr') ?>" required></div>
<div class="col-md-4"><label class="form-label">Surgeon</label><select name="surgeon_id" class="form-select"><option value="0">Select</option><?php foreach ($doctors as $doctor) : ?><option value="<?= (int) ($doctor->id ?? 0) ?>" <?= (int) ($doctor->id ?? 0) === (int) ($case['surgeon_id'] ?? 0) ? 'selected' : '' ?>><?= esc((string) ($doctor->DocSpecName ?? '')) ?></option><?php endforeach ?></select></div>
<div class="col-md-4"><label class="form-label">Anesthetist</label><select name="anesthetist_id" class="form-select"><option value="0">Select</option><?php foreach ($doctors as $doctor) : ?><option value="<?= (int) ($doctor->id ?? 0) ?>" <?= (int) ($doctor->id ?? 0) === (int) ($case['anesthetist_id'] ?? 0) ? 'selected' : '' ?>><?= esc((string) ($doctor->DocSpecName ?? '')) ?></option><?php endforeach ?></select></div>
<?php if (! empty($case['scheduled_start_at'])) : ?><div class="col-md-9"><label class="form-label">Reason for date/time modification</label><input type="text" name="reason" class="form-control" maxlength="255" required></div><?php endif ?><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary w-100" type="submit"><?= empty($case['scheduled_start_at']) ? 'Schedule' : 'Reschedule' ?></button></div></div><div class="ipd-ot-form-notice mt-2"></div></form>
<?php endif ?>
<?php if ($can_status) : ?>
<form class="ipd-ot-ajax-form border rounded p-3 mb-3" action="<?= site_url('ot/cases/' . $caseId) ?>" method="post" data-refresh="queue"><h6>Patient Call Confirmation</h6><?= csrf_field() ?><input type="hidden" name="action" value="call"><div class="row g-2"><div class="col-md-4"><select name="call_status" class="form-select"><option value="called">Called</option><option value="confirmed">Confirmed</option><option value="not_reachable">Not reachable</option><option value="declined">Declined</option></select></div><div class="col-md-5"><input type="text" name="reason" class="form-control" placeholder="Reason/remarks (required if declined)"></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Update Call</button></div></div><div class="ipd-ot-form-notice mt-2"></div></form>
<form class="ipd-ot-ajax-form border rounded p-3" action="<?= site_url('ot/cases/' . $caseId) ?>" method="post" data-refresh="queue"><h6>Safety Checklist &amp; Status</h6><?= csrf_field() ?><input type="hidden" name="action" value="status"><div class="row g-2">
<?php foreach (['consent_verified'=>'Consent','site_side_verified'=>'Patient/Site/Side','allergy_verified'=>'Allergy','npo_verified'=>'NPO/Fasting','investigations_verified'=>'Investigations','anesthesia_clearance'=>'Anesthesia Clearance','who_sign_in'=>'WHO Sign-in','who_time_out'=>'WHO Time-out','who_sign_out'=>'WHO Sign-out'] as $field=>$label) : ?><div class="col-md-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="<?= $field ?>" value="1" <?= ! empty($case[$field]) ? 'checked' : '' ?>><span class="form-check-label"><?= esc($label) ?></span></label></div><?php endforeach ?>
<div class="col-md-4"><label class="form-label">Blood</label><select class="form-select" name="blood_availability"><option value="not_required">Not required</option><option value="arranged" <?= ($case['blood_availability'] ?? '') === 'arranged' ? 'selected' : '' ?>>Arranged</option><option value="available" <?= ($case['blood_availability'] ?? '') === 'available' ? 'selected' : '' ?>>Available</option></select></div>
<div class="col-md-4"><label class="form-label">Next Status</label><select class="form-select" name="status"><?php $statusOptions = ['requested'=>['cancelled'],'scheduled'=>['called','in_progress','cancelled'],'called'=>['scheduled','in_progress','cancelled'],'in_progress'=>['completed']][$status] ?? []; foreach ($statusOptions as $next) : ?><option value="<?= $next ?>"><?= esc(ucwords(str_replace('_',' ',$next))) ?></option><?php endforeach ?></select></div><div class="col-md-4"><label class="form-label">Reason/Notes</label><input class="form-control" name="reason" placeholder="Required for cancellation"></div><div class="col-12 text-end"><button class="btn btn-success">Update Status</button></div></div><div class="ipd-ot-form-notice mt-2"></div></form>
<?php endif ?>
<?php if ($can_postop) : ?><div class="mt-3"><button type="button" class="btn btn-outline-secondary ipd-ot-postop-open" data-case-id="<?= $caseId ?>">Post-operative Assessment</button></div><?php endif ?>
<?= view('ipd_ot/workflow_script') ?>
<script>$(document).off('click.otPostop','.ipd-ot-postop-open').on('click.otPostop','.ipd-ot-postop-open',function(){load_form_div('<?= site_url('ot/cases/' . $caseId . '/postop') ?>',$(this).closest('.modal-body').attr('id'));});</script>