<?php
/** @var array<string, mixed> $case */
/** @var array<int, array<string, mixed>> $assessments */
/** @var bool $can_manage */
$caseId=(int)($case['id']??0);
?>
<h5>Post-operative Assessment &amp; Handover</h5><p class="small text-muted"><?= esc((string)($case['procedure_name']??'')) ?></p>
<?php if ($can_manage) : ?><form class="ipd-ot-ajax-form" action="<?= site_url('ot/cases/'.$caseId.'/postop') ?>" method="post" data-refresh="queue"><?= csrf_field() ?><div class="row g-2">
<div class="col-md-3"><label class="form-label">Observed At</label><input type="datetime-local" class="form-control" name="observed_at" value="<?= date('Y-m-d\TH:i') ?>" required></div><div class="col-md-3"><label class="form-label">Consciousness</label><input class="form-control" name="consciousness"></div><div class="col-md-6"><label class="form-label">Airway/Breathing</label><input class="form-control" name="airway_breathing"></div>
<div class="col-md-2"><label class="form-label">BP</label><input class="form-control" name="bp"></div><div class="col-md-2"><label class="form-label">Pulse</label><input class="form-control" name="pulse"></div><div class="col-md-2"><label class="form-label">SpO2</label><input class="form-control" name="spo2"></div><div class="col-md-2"><label class="form-label">Temperature</label><input class="form-control" name="temperature"></div><div class="col-md-2"><label class="form-label">Pain (0-10)</label><input type="number" min="0" max="10" class="form-control" name="pain_score"></div><div class="col-md-2"><label class="form-label">Nausea/Vomiting</label><input class="form-control" name="nausea_vomiting"></div>
<div class="col-md-6"><label class="form-label">Bleeding/Wound/Drain</label><textarea class="form-control" name="bleeding_wound_drain"></textarea></div><div class="col-md-6"><label class="form-label">Complications</label><textarea class="form-control" name="complications"></textarea></div><div class="col-md-6"><label class="form-label">Interventions</label><textarea class="form-control" name="interventions"></textarea></div><div class="col-md-6"><label class="form-label">Disposition</label><input class="form-control" name="disposition" placeholder="PACU / ICU / Ward"></div><div class="col-12"><label class="form-label">Handover Notes</label><textarea class="form-control" name="handover_notes" required></textarea></div><div class="col-12 text-end"><button class="btn btn-success">Sign Assessment</button></div></div><div class="ipd-ot-form-notice mt-2"></div></form><?php endif ?>
<?php if (!empty($assessments)) : ?><hr><h6>Signed Assessments</h6><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Observed</th><th>Vitals</th><th>Pain</th><th>Disposition/Handover</th></tr></thead><tbody><?php foreach($assessments as $row): ?><tr><td><?= esc((string)$row['observed_at']) ?></td><td>BP <?= esc((string)$row['bp']) ?>, Pulse <?= esc((string)$row['pulse']) ?>, SpO2 <?= esc((string)$row['spo2']) ?></td><td><?= (int)$row['pain_score'] ?></td><td><?= esc((string)$row['disposition']) ?><br><?= esc((string)$row['handover_notes']) ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?>
<?= view('ipd_ot/workflow_script') ?>